/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendamentosIndexRouteImport } from './routes/agendamentos.index'
import { Route as AgendamentosNovoRouteImport } from './routes/agendamentos.novo'
import { Route as AgendamentosIdIndexRouteImport } from './routes/agendamentos.$id.index'
import { Route as AgendamentosIdEditarRouteImport } from './routes/agendamentos.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosIndexRoute = AgendamentosIndexRouteImport.update({
  id: '/agendamentos/',
  path: '/agendamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosNovoRoute = AgendamentosNovoRouteImport.update({
  id: '/agendamentos/novo',
  path: '/agendamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosIdIndexRoute = AgendamentosIdIndexRouteImport.update({
  id: '/agendamentos/$id/',
  path: '/agendamentos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosIdEditarRoute = AgendamentosIdEditarRouteImport.update({
  id: '/agendamentos/$id/editar',
  path: '/agendamentos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/agendamentos/novo': typeof AgendamentosNovoRoute
  '/agendamentos/': typeof AgendamentosIndexRoute
  '/agendamentos/$id/editar': typeof AgendamentosIdEditarRoute
  '/agendamentos/$id/': typeof AgendamentosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/agendamentos/novo': typeof AgendamentosNovoRoute
  '/agendamentos': typeof AgendamentosIndexRoute
  '/agendamentos/$id/editar': typeof AgendamentosIdEditarRoute
  '/agendamentos/$id': typeof AgendamentosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/agendamentos/novo': typeof AgendamentosNovoRoute
  '/agendamentos/': typeof AgendamentosIndexRoute
  '/agendamentos/$id/editar': typeof AgendamentosIdEditarRoute
  '/agendamentos/$id/': typeof AgendamentosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/agendamentos/novo'
    | '/agendamentos/'
    | '/agendamentos/$id/editar'
    | '/agendamentos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/agendamentos/novo'
    | '/agendamentos'
    | '/agendamentos/$id/editar'
    | '/agendamentos/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/agendamentos/novo'
    | '/agendamentos/'
    | '/agendamentos/$id/editar'
    | '/agendamentos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  AgendamentosNovoRoute: typeof AgendamentosNovoRoute
  AgendamentosIndexRoute: typeof AgendamentosIndexRoute
  AgendamentosIdEditarRoute: typeof AgendamentosIdEditarRoute
  AgendamentosIdIndexRoute: typeof AgendamentosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos/': {
      id: '/agendamentos/'
      path: '/agendamentos'
      fullPath: '/agendamentos/'
      preLoaderRoute: typeof AgendamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos/novo': {
      id: '/agendamentos/novo'
      path: '/agendamentos/novo'
      fullPath: '/agendamentos/novo'
      preLoaderRoute: typeof AgendamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos/$id/': {
      id: '/agendamentos/$id/'
      path: '/agendamentos/$id'
      fullPath: '/agendamentos/$id/'
      preLoaderRoute: typeof AgendamentosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos/$id/editar': {
      id: '/agendamentos/$id/editar'
      path: '/agendamentos/$id/editar'
      fullPath: '/agendamentos/$id/editar'
      preLoaderRoute: typeof AgendamentosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  AgendamentosNovoRoute: AgendamentosNovoRoute,
  AgendamentosIndexRoute: AgendamentosIndexRoute,
  AgendamentosIdEditarRoute: AgendamentosIdEditarRoute,
  AgendamentosIdIndexRoute: AgendamentosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
